export const TEST_IDS = {
  CREATE_NEW_USER_BUTTON: 'CreateNewUserButton',
  CHOOSE_NAME_ADVANCE_BUTTON: 'ChooseNameAdvanceButton',
  CONFIRM_NEW_PASSWORD_INPUT: 'confirmNewPasswordInput',
  EMAIL_INPUT: 'EMAIL_INPUT',
  CHOOSE_THEME_ADVANCE_BUTTON: 'ChooseThemeAdvanceButton',
  SAVE_USER_CONFIGURATIONS_BUTTON: 'SaveUserConfigurationSaveButton',
  HEADER_USER_NAME_TEXT: 'HeaderUserNameText',
  WELCOME_SCREEN_WRAPPER: 'WelcomeScreenWrapper',
  NEW_PASSWORD_INPUT: 'NewPasswordInput',
  TEXT_BASE: 'text-base',
  THEME_BOX_BLUE_GREEN: 'ThemeBox-BLUE_GREEN',
  THEME_BOX_BLUE_RED: 'ThemeBox-BLUE_RED',
  FONT_AWESOME_ICON_5: 'FontAwesomeIcon5',
  NAVIGATE_BUTTON_TITLE: 'NavigateButton-title',
  TEXT_BUTTON_ICON: 'TextButtonIcon',
  OUTLINE_BUTTON_TEXT: 'OutlineButton-text',
  ERROR_PAGE_CONTAINER: 'ErrorPageContainer',
  IMAGE_AVATAR: 'ImageAvatar',
  BUTTON_BASE: 'ButtonBase',
  RELOAD_APP_BUTTON: 'ReloadAppButton',
  CATEGORY_COLOR_BOX_TRANSPARENT_VIEW: 'CategoryColorBoxTransparentView',
  CATEGORY_COLOR_BOX_LINEAR_GRADIENT: 'CategoryColorBoxLinearGradient',
};
