export const TEST_IDS = {
  CREATE_NEW_USER_BUTTON: 'CreateNewUserButton',
  CHOOSE_NAME_ADVANCE_BUTTON: 'ChooseNameAdvanceButton',
  CONFIRM_NEW_PASSWORD_INPUT: 'confirmNewPasswordInput',
  EMAIL_INPUT: 'EMAIL_INPUT',
  CHOOSE_THEME_ADVANCE_BUTTON: 'ChooseThemeAdvanceButton',
  SAVE_USER_CONFIGURATIONS_BUTTON: 'SaveUserConfigurationSaveButton',
  HEADER_USER_NAME_TEXT: 'HeaderUserNameText',
  WELCOME_SCREEN_WRAPPER: 'WelcomeScreenWrapper',
  NEW_PASSWORD_INPUT: 'NewPasswordInput',
  TEXT_BASE: 'text-base',
  THEME_BOX_BLUE_GREEN: 'ThemeBox-BLUE_GREEN',
  THEME_BOX_BLUE_RED: 'ThemeBox-BLUE_RED',
  FONT_AWESOME_ICON_5: 'FontAwesomeIcon5',
  NAVIGATE_BUTTON_TITLE: 'NavigateButton-title',
  TEXT_BUTTON_ICON: 'TextButtonIcon',
  OUTLINE_BUTTON_TEXT: 'OutlineButton-text',
  ERROR_PAGE_CONTAINER: 'ErrorPageContainer',
  IMAGE_AVATAR: 'ImageAvatar',
  BUTTON_BASE: 'ButtonBase',
  RELOAD_APP_BUTTON: 'ReloadAppButton',
  CATEGORY_COLOR_BOX_TRANSPARENT_VIEW: 'CategoryColorBoxTransparentView',
  CATEGORY_COLOR_BOX_LINEAR_GRADIENT: 'CategoryColorBoxLinearGradient',
  LOADING_INDICATOR_BASE: 'loading-indicator-base',
  ACTIVITY_INDICATOR_BASE: 'activity-indicator-base',
  ERROR_MESSAGE: 'ErrorMessage',
  FLAT_LIST_WITH_FETCH_INDICATOR_FLAT_LIST:
    'FlatListWithFetchIndicatorFlatList',
  FLAT_LIST_WITH_FETCH_INDICATOR_REFRESH_CONTROL:
    'FlatListWithFetchIndicatorRefreshControl',
  PRIMARY_HEADER_CONTAINER: 'PrimaryHeaderContainer',
  SECONDARY_HEADER_CONTAINER: 'SecondaryHeaderContainer',
  PRIMARY_HEADER_BACK_BUTTON: 'PrimaryHeaderBackButton',
  SECONDARY_HEADER_BACK_BUTTON: 'SecondaryHeaderBackButton',
  SECTION_CONTAINER: 'SectionContainer',
  SECTION_CONTENT_CONTAINER: 'SectionContentContainer',
  SEPARATOR: 'Separator',
  SHADOW: 'Shadow',
  TOAST: 'Toast',
  THEME_BOX_VIEW_PRIMARY_COLOR: 'ThemeBoxViewPrimaryColor',
  THEME_BOX_VIEW_SECONDARY_COLOR: 'ThemeBoxViewSecondaryColor',
};
